// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtmsrknHjayEo7qYFVemf5tZEpAjsshq8',
    appId: '1:936559988864:web:4c12dd8c84fe57a5f05665',
    messagingSenderId: '936559988864',
    projectId: 'fruits-hub-f83ad',
    authDomain: 'fruits-hub-f83ad.firebaseapp.com',
    storageBucket: 'fruits-hub-f83ad.firebasestorage.app',
    measurementId: 'G-7NQZBVJRZH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLUQCVcWXE1eUPIgZU7_C3_sSofuLlsyE',
    appId: '1:936559988864:android:97ff028a70e74e57f05665',
    messagingSenderId: '936559988864',
    projectId: 'fruits-hub-f83ad',
    storageBucket: 'fruits-hub-f83ad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJ_rUbyZrYqT4FVzew7qUJelcnLHAAasA',
    appId: '1:936559988864:ios:ce8afab49491ece5f05665',
    messagingSenderId: '936559988864',
    projectId: 'fruits-hub-f83ad',
    storageBucket: 'fruits-hub-f83ad.firebasestorage.app',
    iosBundleId: 'com.example.fruitsHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJ_rUbyZrYqT4FVzew7qUJelcnLHAAasA',
    appId: '1:936559988864:ios:ce8afab49491ece5f05665',
    messagingSenderId: '936559988864',
    projectId: 'fruits-hub-f83ad',
    storageBucket: 'fruits-hub-f83ad.firebasestorage.app',
    iosBundleId: 'com.example.fruitsHub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBtmsrknHjayEo7qYFVemf5tZEpAjsshq8',
    appId: '1:936559988864:web:df4001a34f8424a7f05665',
    messagingSenderId: '936559988864',
    projectId: 'fruits-hub-f83ad',
    authDomain: 'fruits-hub-f83ad.firebaseapp.com',
    storageBucket: 'fruits-hub-f83ad.firebasestorage.app',
    measurementId: 'G-EMT9PEYDP9',
  );
}
